In [1]:
import numpy as np
import pandas as pd

In [53]:
# Question 1

genderCount = {'Boys': [72, 68, 70, 69, 74], 'Girls': [63, 65, 69, 62, 61]}

res = []

for i in range(len(genderCount['Boys'])):
    res.append({ 'Boys': genderCount['Boys'][i], 'Girls': genderCount['Girls'][i] })

print(res)

[{'Boys': 72, 'Girls': 63}, {'Boys': 68, 'Girls': 65}, {'Boys': 70, 'Girls': 69}, {'Boys': 69, 'Girls': 62}, {'Boys': 74, 'Girls': 61}]


In [65]:
# Question 2

# 2.1

arr = np.random.randint(low=0, high=100, size=(4,4))
print(arr)
print(np.mean(arr, axis=1))
print(np.std(arr, axis=1))
print(np.var(arr, axis=1))

[[11 75 92 69]
 [59  1 27 24]
 [34 60 36 84]
 [15 53  4 84]]
[61.75 27.75 53.5  39.  ]
[30.49077729 20.65641547 20.36541185 31.70961999]
[ 929.6875  426.6875  414.75   1005.5   ]


In [58]:
# 2.2

arr = np.random.randint(low=0, high=100, size=(7,))
print(arr)
np.argsort(arr)

[47 42 92 12 28 66 75]


array([3, 4, 1, 0, 5, 6, 2], dtype=int64)

In [75]:
# 2.3

m, n = input().split(" ")
m, n = int(m), int(n)

arr = np.random.randint(low=0, high=100, size=(m, n))

print("Shape:", arr.shape)
print("Dimensionality: ", len(arr.shape), 'D', sep='')
print("Data Type:", arr.dtype)

m, n = input().split(" ")
m, n = int(m), int(n)

try:
    print("Reshaped array:\n", arr.reshape(n, m))

except:
    print(f'Cannot reshape array of size {arr.size} into shape ({m}, {n}).')

45 47
Shape: (45, 47)
Dimensionality: 2D
Data Type: int32
212 5
Cannot reshape array of size 2115 into shape (212, 5).


In [63]:
# 2.4

arr = np.random.choice([0, 1, np.nan], (10,))
print('Generated array :', arr)

zeroes = np.where(arr == 0)
nans = np.where(np.isnan(arr))
nzeroes = np.array([i for i in range(len(arr)) if arr[i] != 0 and np.isnan(arr[i]) == False])

print('Zeroes:', zeroes)
print('NaNs:', nans)
print('Non-Zeroes:', nzeroes)

Generated array : [ 0.  1. nan  0.  0. nan nan  1.  1.  0.]
Zeroes: (array([0, 3, 4, 9], dtype=int64),)
NaNs: (array([2, 5, 6], dtype=int64),)
Non-Zeroes: [1 7 8]
