## Q1
1. Consider a list of values:
bag = [25,26,21,22,31,29,33,34,26,30,31,46]

In [3]:
import numpy as np

bag = [25, 26, 21, 22, 31, 29, 33, 34, 26, 30, 31, 46]
bag_weights = np.array(bag).reshape(3, 4)
bag
bag_weights

array([[25, 26, 21, 22],
       [31, 29, 33, 34],
       [26, 30, 31, 46]])

In [4]:
mean_value = np.mean(bag_weights)
variance_value = np.var(bag_weights)
median_value = np.median(bag_weights)

print("Mean:", mean_value)
print("Variance:", variance_value)
print("Median:", median_value)


Mean: 29.5
Variance: 40.25
Median: 29.5


In [5]:
count_greater_than_median = np.sum(bag_weights > median_value)
print("Count of values greater than the median:", count_greater_than_median)


Count of values greater than the median: 6


In [7]:
transposed_bag_weights = np.transpose(bag_weights)
bagA, bagB = np.split(transposed_bag_weights, 2)
transposed_bag_weights

array([[25, 31, 26],
       [26, 29, 30],
       [21, 33, 31],
       [22, 34, 46]])

In [10]:
# Sort bagA in descending order based on the first column
bagA = bagA[np.argsort(bagA[:, 0])[::-1]]

# Sort bagB in ascending order based on the first column
bagB = bagB[np.argsort(bagB[:, 0])]

bagA

array([[26, 29, 30],
       [25, 31, 26]])

In [11]:
bagB

array([[21, 33, 31],
       [22, 34, 46]])

In [9]:
union_result = np.union1d(bagA, bagB)
intersection_result = np.intersect1d(bagA, bagB)

print("Union of bagA and bagB:", union_result)
print("Intersection of bagA and bagB:", intersection_result)


Union of bagA and bagB: [21 22 25 26 29 30 31 33 34 46]
Intersection of bagA and bagB: [31]
