In [1]:
import numpy as np

In [2]:
data=np.random.randn(2,3)

In [3]:
data

array([[-1.66537628, -0.45156431,  1.07042547],
       [-2.7464236 ,  0.43458145, -1.05874422]])

In [4]:
data*100

array([[-166.53762787,  -45.1564313 ,  107.04254715],
       [-274.64236001,   43.45814527, -105.87442224]])

In [5]:
data

array([[-1.66537628, -0.45156431,  1.07042547],
       [-2.7464236 ,  0.43458145, -1.05874422]])

In [6]:
data=data+data

In [7]:
data

array([[-3.33075256, -0.90312863,  2.14085094],
       [-5.4928472 ,  0.86916291, -2.11748844]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [10]:
data1=[1,3,5,7]

In [11]:
arr1=np.array(data1)

In [12]:
arr1

array([1, 3, 5, 7])

In [13]:
arr1.ndim

1

In [14]:
arr2=np.array([[1,2],[3,4]])

In [15]:
arr2

array([[1, 2],
       [3, 4]])

In [16]:
arr2.shape

(2, 2)

In [17]:
arr2.ndim

2

In [18]:
arr2.dtype

dtype('int32')

In [19]:
arr1=np.zeros(10)

In [20]:
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.empty(2)

array([0., 0.])

In [22]:
arr3=np.arange(15)

In [23]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
arr4=np.identity(5)

In [25]:
import numpy as np
arr5=np.eye(5,5)


In [26]:
np.array(np.arange(5),dtype=np.float64)

array([0., 1., 2., 3., 4.])

In [27]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
arr6=np.array(arr4,dtype=np.float32)

In [29]:
arr6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [30]:
int_arr6=arr6.astype(np.int32)

In [31]:
int_arr6

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [32]:
arr7=np.array(['1','2.4','8'],dtype=np.string_)

In [33]:
arr7

array([b'1', b'2.4', b'8'], dtype='|S3')

In [34]:
arr7.dtype

dtype('S3')

In [35]:
n_str=arr7.astype(arr6.dtype)

In [36]:
n_str

array([1. , 2.4, 8. ], dtype=float32)

In [37]:
arr=np.array(np.arange(5))

In [38]:
arr

array([0, 1, 2, 3, 4])

In [39]:
arr+arr

array([0, 2, 4, 6, 8])

In [40]:
arr-arr

array([0, 0, 0, 0, 0])

In [41]:
arr*arr

array([ 0,  1,  4,  9, 16])

In [42]:
arr**3

array([ 0,  1,  8, 27, 64], dtype=int32)

In [43]:
arr//arr

<ipython-input-43-90585fabb6b0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  arr//arr


array([0, 1, 1, 1, 1], dtype=int32)

In [44]:
1/arr

<ipython-input-44-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [45]:
arr2=np.array([5,6,7,8,9])

In [46]:
arr

array([0, 1, 2, 3, 4])

In [47]:
arr2

array([5, 6, 7, 8, 9])

In [48]:
arr+arr2

array([ 5,  7,  9, 11, 13])

In [49]:
arr>arr2

array([False, False, False, False, False])

In [50]:
arr1=np.arange(10)

In [51]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr1[4:7]=50

In [53]:
arr1

array([ 0,  1,  2,  3, 50, 50, 50,  7,  8,  9])

In [54]:
slice1=arr1[5:7]

In [55]:
slice1

array([50, 50])

In [56]:
slice1[:]=89

In [57]:
arr1

array([ 0,  1,  2,  3, 50, 89, 89,  7,  8,  9])

In [124]:
arr2d=np.array([[2,3],[9,5],[6,8]])
arr2d

array([[2, 3],
       [9, 5],
       [6, 8]])

In [59]:
arr2d[2]

array([6, 8])

In [60]:
arr2d[1][0]

9

In [120]:
arr3d=np.array([[[1,2],[4,8]],[[3,5],[8,1]]])

In [121]:
arr3d.shape

(2, 2, 2)

In [63]:
arr3d[0]

array([[1, 2],
       [4, 8]])

In [64]:
arr3d[0][0]

array([1, 2])

In [65]:
arr3d[0][1][1]

8

In [66]:
old_values=arr3d

In [67]:
old_values

array([[[1, 2],
        [4, 8]],

       [[3, 5],
        [8, 1]]])

In [122]:
a2d=[[5,6],[8,9]]
print(type(a2d))

<class 'list'>


In [69]:
arr3d[0][1]=90

In [70]:
arr3d

array([[[ 1,  2],
        [90, 90]],

       [[ 3,  5],
        [ 8,  1]]])

In [71]:
old_values

array([[[ 1,  2],
        [90, 90]],

       [[ 3,  5],
        [ 8,  1]]])

In [72]:
arr3d_copy=arr3d.copy()

In [73]:
arr3d[1]=12

In [74]:
arr3d

array([[[ 1,  2],
        [90, 90]],

       [[12, 12],
        [12, 12]]])

In [75]:
arr3d_copy

array([[[ 1,  2],
        [90, 90]],

       [[ 3,  5],
        [ 8,  1]]])

In [116]:
arr3d_copy[1][1][0]=56
arr3d_copy

array([[[ 1,  2],
        [90, 90]],

       [[ 3,  5],
        [56, 50]]])

In [125]:
arr2d

array([[2, 3],
       [9, 5],
       [6, 8]])

In [126]:
arr2d[:2,0]

array([2, 9])

In [127]:
arr2d[:2,:2]=0

In [128]:
arr2d

array([[0, 0],
       [0, 0],
       [6, 8]])

In [81]:
names=np.array(['a','b','c'])

In [129]:
data=np.random.randn(3,4)

In [130]:
names

array(['a', 'b', 'c'], dtype='<U1')

In [131]:
data

array([[ 0.33316197, -0.94338532, -1.0181979 , -0.0708101 ],
       [ 1.20675463, -1.60912735, -0.84067135, -0.26097724],
       [-1.22641137,  1.31161896,  0.44569335,  0.48197102]])

In [132]:
names=='b'

array([False,  True, False])

In [133]:
data[names=='b']

array([[ 1.20675463, -1.60912735, -0.84067135, -0.26097724]])

In [134]:
data[names=='a',2:]

array([[-1.0181979, -0.0708101]])

In [88]:
data[names!='a']

array([[ 0.2947283 , -0.72685558, -0.40733355, -0.20444261],
       [ 0.06059076,  0.70323252,  0.0915978 , -0.07129698]])

In [89]:
data[~(names=='b')]

array([[ 0.56809459, -0.24307742, -0.91505467,  1.43382165],
       [ 0.06059076,  0.70323252,  0.0915978 , -0.07129698]])

In [135]:
data[data<0]=10

In [139]:
data

array([[ 0.33316197, 10.        , 10.        , 10.        ],
       [ 1.20675463, 10.        , 10.        , 10.        ],
       [10.        ,  1.31161896,  0.44569335,  0.48197102]])

In [137]:
mask=(names=='a')|(names=='c')

In [138]:
data[~mask]

array([[ 1.20675463, 10.        , 10.        , 10.        ]])

In [140]:
data[names=='b']

array([[ 1.20675463, 10.        , 10.        , 10.        ]])

In [143]:
arr=np.empty((3,4))

In [144]:
for i in range(3):
    arr[i]=i

In [145]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.]])

In [146]:
arr[[2,0]]

array([[2., 2., 2., 2.],
       [0., 0., 0., 0.]])

In [99]:
arr[[-3]]

array([[0., 0., 0., 0.]])

In [148]:
arr1=np.arange(32).reshape(8,4)

In [149]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [147]:
selectedi=np.array([[2,3],[0,7]])

In [150]:
selectedi

array([[2, 3],
       [0, 7]])

In [152]:
arr1[selectedi]

array([[[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[ 0,  1,  2,  3],
        [28, 29, 30, 31]]])

In [154]:
arr1[[2,3,4],[0,1,3]]

array([ 8, 13, 19])

In [155]:
arr=np.arange(20).reshape(5,4)

In [156]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [157]:
arr.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [159]:
arr3d=np.arange(30).reshape(5,3,2)

In [160]:
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [161]:
arr3d.swapaxes(1,2)

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]],

       [[12, 14, 16],
        [13, 15, 17]],

       [[18, 20, 22],
        [19, 21, 23]],

       [[24, 26, 28],
        [25, 27, 29]]])

In [162]:
arr3d.swapaxes(0,1)

array([[[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]],

       [[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27]],

       [[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29]]])

In [163]:
arr3d.swapaxes(0,2)

array([[[ 0,  6, 12, 18, 24],
        [ 2,  8, 14, 20, 26],
        [ 4, 10, 16, 22, 28]],

       [[ 1,  7, 13, 19, 25],
        [ 3,  9, 15, 21, 27],
        [ 5, 11, 17, 23, 29]]])

In [164]:
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [168]:
arr3d.T

array([[[ 0,  6, 12, 18, 24],
        [ 2,  8, 14, 20, 26],
        [ 4, 10, 16, 22, 28]],

       [[ 1,  7, 13, 19, 25],
        [ 3,  9, 15, 21, 27],
        [ 5, 11, 17, 23, 29]]])

In [169]:
arr3d.transpose(1,2,0)

array([[[ 0,  6, 12, 18, 24],
        [ 1,  7, 13, 19, 25]],

       [[ 2,  8, 14, 20, 26],
        [ 3,  9, 15, 21, 27]],

       [[ 4, 10, 16, 22, 28],
        [ 5, 11, 17, 23, 29]]])