In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [11]:
a1=np.zeros(10)

In [12]:
a1[4]=1

In [13]:
a11=np.arange(10,50)

In [14]:
a11

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
np.flip(a11)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [21]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
np.nonzero(a11)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39], dtype=int64),)

In [26]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
r1=np.random.randn(3,3,3)

In [28]:
r1

array([[[ 1.58924236, -0.8360016 , -0.34780693],
        [-0.62898351,  1.19508245,  1.26857505],
        [ 0.09244027,  0.41539745, -0.42400005]],

       [[-2.09678575, -2.0196219 , -1.91952699],
        [-0.16654901, -2.47688055,  0.34741429],
        [ 0.63655936, -0.45993666, -0.25003991]],

       [[-1.08812906,  0.728236  , -1.85478164],
        [ 0.810882  ,  0.03556259, -0.06519374],
        [ 0.40052197,  0.4484202 , -1.1243422 ]]])

In [29]:
np.min(r1)

-2.4768805493887798

In [30]:
np.mean(np.random.rand(30))

0.420341980438503

In [31]:
0*np.nan

nan

In [32]:
np.nan==np.nan

False

In [33]:
np.inf>np.nan

False

In [34]:
np.nan-np.nan

nan

In [35]:
np.nan in set([np.nan])

True

In [36]:
0.3==3*0.1

False

In [37]:
a=3*0.1

In [38]:
a

0.30000000000000004

In [44]:
a55=np.zeros((5,5))

In [45]:
a55

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [48]:
a55.ndim

2