In [3]:
import numpy as np
L1=list(range(100000))
ar1=np.arange(100000)

In [4]:
%time for i in range(10): L1:2*L1

Wall time: 31 ms


In [5]:
%time for i in range(10): ar1:2*ar1

Wall time: 6.25 ms


In [6]:
thr3=np.full((4,4),3)

In [7]:
ze2=np.zeros((2,2))

In [8]:
thr3[1:3,1:3]=ze2

In [9]:
thr3

array([[3, 3, 3, 3],
       [3, 0, 0, 3],
       [3, 0, 0, 3],
       [3, 3, 3, 3]])

In [11]:
m1=np.diag((4,4,1,6,4))

In [9]:
m1

array([[4, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 4]])

In [12]:
nr,nc=np.shape(m1)

In [13]:
nr,nc

(5, 5)

In [ ]:
np.size(m1)

In [ ]:
m1.dtype

In [ ]:
m1.shape

In [ ]:
m1.size

In [ ]:
m1.dtype

In [ ]:
m1.ndim

In [ ]:
a=np.array([3,6,8])

In [ ]:
a.ndim

In [ ]:
b=np.empty((4,4))

In [ ]:
b


In [ ]:
bz=np.zeros((4,5))

In [ ]:
bz

In [ ]:
bfull=np.full((3,4),5)

In [ ]:
bfull

In [ ]:
b1=([1,3,4,5,6,7])

In [ ]:
b1

In [ ]:
b1=np.array(b1)

In [ ]:
b1

In [ ]:
b1[3]

In [ ]:
b1[1:3]

In [ ]:
b1

In [ ]:
b1[-4:-2]

In [ ]:
b1[b1%2==0]

In [ ]:
b1[b1>3]

In [17]:
b11=np.array([[1,3,5],[3,4,5],[3,6,7]])

In [18]:
b11

array([[1, 3, 5],
       [3, 4, 5],
       [3, 6, 7]])

In [ ]:
b11[1]

In [ ]:
b11[:,1]

In [20]:
b11[2,1]

6

In [ ]:
b11[0:2,1:3]

In [19]:
b11[b11>3]

array([5, 4, 5, 6, 7])

In [ ]:
b11[]

In [21]:
m1=np.array([1,4,6,7,9])

In [22]:
m1

array([1, 4, 6, 7, 9])

In [23]:
m11=np.array([[1,3,6],[5,6,7],[3,6,9]])

In [24]:
m11

array([[1, 3, 6],
       [5, 6, 7],
       [3, 6, 9]])

In [25]:
m111=np.array([[[1,3,4],[3,4,5]],[[3,6,8],[5,6,8]]])

In [26]:
m111

array([[[1, 3, 4],
        [3, 4, 5]],

       [[3, 6, 8],
        [5, 6, 8]]])

In [27]:
m111.ndim

3

In [28]:
m111.shape

(2, 2, 3)

In [29]:
m111.size

12

In [30]:
m111.dtype

dtype('int32')

In [31]:
m11.shape

(3, 3)

In [33]:
m1.shape

(5,)

In [37]:
m34=np.random.randn(3,4)

In [38]:
m34

array([[-0.13405687, -2.2276408 , -0.71629321, -0.16071703],
       [-0.00624176,  0.00543031,  0.00934655, -1.05151261],
       [-0.33052008, -0.88626281,  0.92048991, -1.6972126 ]])

In [39]:
m3=np.arange(10)

In [40]:
m3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
m25=m3.reshape(2,5)

In [45]:
m25

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
m4=np.arange(8)

In [21]:
m4

array([0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
m4.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
m4

array([0, 1, 2, 3, 4, 5, 6, 7])

In [23]:
b1=np.array(['a','b','c','a','c','c','b','a'])

In [61]:
b1=='a'

array([ True, False, False,  True, False, False, False,  True])

In [24]:
m4[b1=='a']

array([0, 3, 7])

In [18]:
m41=m4.reshape(8,2)

In [71]:
m41

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [72]:
m41[b1=='a']

array([[ 0,  1],
       [ 6,  7],
       [14, 15]])

In [99]:
r1=np.random.randint(low=1,high=15,size=(8,3,3))

In [80]:
r1

array([[[ 8,  6,  5],
        [12,  1, 11],
        [11,  7,  6]],

       [[ 5, 13,  9],
        [ 7,  2, 10],
        [12,  5, 11]],

       [[ 2,  1,  6],
        [12,  1, 12],
        [ 6,  8, 11]],

       [[11,  7,  3],
        [ 7,  5,  2],
        [14, 10,  6]],

       [[ 8,  6, 11],
        [ 4,  7,  1],
        [ 6, 10,  1]],

       [[ 3,  8,  3],
        [ 6,  2, 11],
        [ 5,  5, 12]],

       [[ 2,  3, 12],
        [12, 11,  6],
        [ 4, 10,  4]],

       [[ 3,  8,  2],
        [ 1,  2, 12],
        [14,  5,  8]]])

In [82]:
r1[b1=='a']

array([[[ 8,  6,  5],
        [12,  1, 11],
        [11,  7,  6]],

       [[11,  7,  3],
        [ 7,  5,  2],
        [14, 10,  6]],

       [[ 3,  8,  2],
        [ 1,  2, 12],
        [14,  5,  8]]])

In [83]:
m1.T

array([1, 4, 6, 7, 9])

In [84]:
m11.T

array([[1, 5, 3],
       [3, 6, 6],
       [6, 7, 9]])

In [90]:
cond=(b1=='a')|( b1=='b')

In [91]:
cond

array([ True,  True, False,  True, False, False,  True,  True])

In [92]:
m41[~cond]

array([[ 4,  5],
       [ 8,  9],
       [10, 11]])

In [93]:
m41[m41>5]=0

In [94]:
m41

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [97]:
r1[(r1<10)]=0

In [98]:
r1

array([[[ 0,  0,  0],
        [12,  0, 11],
        [11,  0,  0]],

       [[ 0, 13,  0],
        [ 0,  0, 10],
        [12,  0, 11]],

       [[ 0,  0,  0],
        [12,  0, 12],
        [ 0,  0, 11]],

       [[11,  0,  0],
        [ 0,  0,  0],
        [14, 10,  0]],

       [[ 0,  0, 11],
        [ 0,  0,  0],
        [ 0, 10,  0]],

       [[ 0,  0,  0],
        [ 0,  0, 11],
        [ 0,  0, 12]],

       [[ 0,  0, 12],
        [12, 11,  0],
        [ 0, 10,  0]],

       [[ 0,  0,  0],
        [ 0,  0, 12],
        [14,  0,  0]]])

In [100]:
r1[~(r1>5)]=0

In [101]:
r1

array([[[ 0,  9,  6],
        [ 0,  7,  8],
        [14,  0, 11]],

       [[ 0, 10, 13],
        [ 8,  0, 13],
        [ 7, 11, 11]],

       [[11,  7,  8],
        [10,  0,  9],
        [10,  0, 14]],

       [[11,  0,  8],
        [ 7,  0,  8],
        [10,  0, 11]],

       [[10,  0, 11],
        [ 0,  0,  0],
        [12,  0, 13]],

       [[ 8,  8, 10],
        [11, 14,  0],
        [ 8, 14, 11]],

       [[ 0,  0, 11],
        [ 0,  0,  7],
        [11,  0,  6]],

       [[ 0, 14, 11],
        [14,  0,  0],
        [ 6, 11,  9]]])

In [103]:
ar1=np.empty((8,4))

In [104]:
ar1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [105]:
for i in range(8):
    ar1[i]=i

In [106]:
ar1

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [107]:
ar1[[4,3,1,5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.],
       [5., 5., 5., 5.]])

In [108]:
ar1[[-4,-1,-5]]

array([[4., 4., 4., 4.],
       [7., 7., 7., 7.],
       [3., 3., 3., 3.]])

In [109]:
ar1

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [26]:
ar3d=np.arange(24)

In [27]:
ar3d=ar3d.reshape(2,3,4)

In [28]:
ar3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [38]:
ar3d[[0,1]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [43]:
ar3d[[1]]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [47]:
ar3d[1,1]

array([16, 17, 18, 19])

In [49]:
ar3d[0,2,1]

9

In [115]:
ar3d[[[1,0]]]

<ipython-input-115-d97fb417ef87>:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  ar3d[[[1,0]]]


array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [116]:
ar1

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [124]:
ar11[[1,0,2],[1,3,0]]

array([14,  7, 14])

In [127]:
ar11=np.random.randint(low=0,high=15,size=(8,4))

In [122]:
ar11

array([[ 8,  7, 13,  7],
       [11, 14, 13,  7],
       [14,  9,  7,  5]])

In [128]:
ar11

array([[ 6, 14,  0,  4],
       [ 8,  3, 10, 11],
       [ 4,  2, 11,  5],
       [14, 14,  3,  1],
       [12, 10,  5,  9],
       [12,  7,  8, 11],
       [13,  5,  0,  3],
       [ 4,  0,  6, 13]])

In [129]:
ar11[[1,5,7,2]][:,[0,3,1,2]]

array([[ 8, 11,  3, 10],
       [12, 11,  7,  8],
       [ 4, 13,  0,  6],
       [ 4,  5,  2, 11]])

In [131]:
ar11.T

array([[ 6,  8,  4, 14, 12, 12, 13,  4],
       [14,  3,  2, 14, 10,  7,  5,  0],
       [ 0, 10, 11,  3,  5,  8,  0,  6],
       [ 4, 11,  5,  1,  9, 11,  3, 13]])

In [133]:
ar11.transpose((1,0))

array([[ 6,  8,  4, 14, 12, 12, 13,  4],
       [14,  3,  2, 14, 10,  7,  5,  0],
       [ 0, 10, 11,  3,  5,  8,  0,  6],
       [ 4, 11,  5,  1,  9, 11,  3, 13]])

In [134]:
ar3d.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [135]:
ar3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [136]:
ar3d.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [137]:
ar3d.transpose((0,2,1))

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [138]:
ar11

array([[ 6, 14,  0,  4],
       [ 8,  3, 10, 11],
       [ 4,  2, 11,  5],
       [14, 14,  3,  1],
       [12, 10,  5,  9],
       [12,  7,  8, 11],
       [13,  5,  0,  3],
       [ 4,  0,  6, 13]])

In [139]:
ar11t=ar11.T

In [140]:
np.dot(ar11,ar11.T)

array([[248, 134,  72, 284, 248, 214, 160,  76],
       [134, 294, 203, 195, 275, 318, 152, 235],
       [ 72, 203, 166, 122, 168, 205,  77, 147],
       [284, 195, 122, 402, 332, 301, 255,  87],
       [248, 275, 168, 332, 350, 353, 233, 195],
       [214, 318, 205, 301, 353, 378, 224, 239],
       [160, 152,  77, 255, 233, 224, 203,  91],
       [ 76, 235, 147,  87, 195, 239,  91, 221]])

In [142]:
np.dot(ar11.T,ar11)

array([[785, 581, 346, 477],
       [581, 579, 200, 295],
       [346, 200, 355, 379],
       [477, 295, 379, 543]])